In [1]:
#sympy와 비교 검증
import numpy as np
import sympy as sym
import UncertaintyPy as upy

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
upy.ufloat(59, 12)
upy.ufloat(59, 10)
upy.ufloat(59, 9)
upy.ufloat(986.2735, 0.000358)
upy.ufloat(36.5, 100)
upy.ufloat(36.5, 100.1)
upy.ufloat(4.5, 1)
upy.ufloat(7.1278, 0.098)


(6 ± 1)x10

(6 ± 1)x10

59 ± 9

(9862735 ± 4)x10^4

(0 ± 1)x10^2

(0 ± 1)x10^2

5 ± 1

7.1 ± 0.1

In [4]:
a,b,c = sym.symbols("a b c")
u1 = upy.ufloat(1.5, 0.2, "m")
u2 = upy.ufloat(3, 1.5, "m")
u3 = upy.ufloat(7.78, 0.987)

In [5]:
a
b
c
u1
u2
u3

a

b

c

(1.5 ± 0.2) m

(3 ± 2) m

8 ± 1

In [6]:
#add
func1 = upy.ufunc(a + b, [a, b])
func1
func1.f([u1, u2]).set_unit("m")
(u1 + u2).set_unit("m")

func1.f([u1, u2]).uncertainty
(u1 + u2).uncertainty

a + b

(5 ± 2) m

(5 ± 2) m

1.5132745950421556

1.5132745950421556

In [7]:

func2 = upy.ufunc(a + b + c, [a, b, c])
func2
func2.f([u1, u2, u3], "m")
(u1 + u2 + u3).set_unit("m")

func2.f([u1, u2, u3], "m").uncertainty
(u1 + u2 + u3).uncertainty

a + b + c

(12 ± 2) m

(12 ± 2) m

1.8067011374325306

1.8067011374325306

In [8]:
#sub
func3 = upy.ufunc(a - b, [a, b])
func3
func3.f([u1, u2]).set_unit("m")
(u1 - u2).set_unit("m")

func3.f([u1, u2]).uncertainty
(u1 - u2).uncertainty

a - b

(-2 ± 2) m

(-2 ± 2) m

1.5132745950421556

1.5132745950421556

In [9]:
#mul
func4 = upy.ufunc(a*b, [a,b])
func4
func4.f([u1, u2])
u1*u2

func4.f([u1, u2]).uncertainty
(u1*u2).uncertainty

a*b

5 ± 2

5 ± 2

2.328626204439004

2.328626204439004

In [10]:
#div
func5 = upy.ufunc(a/b, [a,b])
func5
func5.f([u1, u2])
u1/u2

func5.f([u1, u2]).uncertainty
(u1/u2).uncertainty

a/b

0.5 ± 0.3

0.5 ± 0.3

0.25873624493766706

0.25873624493766706

In [11]:
#pow
func6 = upy.ufunc(a**3, [a])
func6
func6.f([u1])
u1**3

func6.f([u1]).uncertainty
(u1**3).uncertainty

a**3

3 ± 1

3 ± 1

1.35

1.35

In [12]:
func7 = upy.ufunc(a*b/c, [a, b, c])
func7
func7.f([u1,u2,u3])
u1*u2/u3

func7.f([u1,u2,u3]).uncertainty
(u1*u2/u3).uncertainty

a*b/c

0.6 ± 0.3

0.6 ± 0.3

0.30817282579065397

0.308172825790654

In [13]:
func8 = upy.ufunc(5*a/b**3-c, [a, b, c])
func8
func8.f([u1, u2, u3])
5*u1/u2**3-u3

func8.f([u1, u2, u3]).uncertainty
(5*u1/u2**3-u3).uncertainty

5*a/b**3 - c

-8 ± 1

-8 ± 1

1.071985006062862

1.071985006062862

In [32]:
#exp
func9 = upy.ufunc(sym.exp(a), [a])
func9
func9.f([u1])
upy.exp(u1)

func9.f([u1]).uncertainty
upy.exp(u1).uncertainty

upy.exp([u1, u2, u2])
upy.exp(np.array([u1, u2, u3]))

exp(a)

4 ± 1

4 ± 1

0.8963378140676129

0.8963378140676129

array([4 ± 1, (2 ± 3)x10, (2 ± 3)x10], dtype=object)

array([4 ± 1, (2 ± 3)x10, (2 ± 2)x10^3], dtype=object)

In [31]:
#log base
func10 = upy.ufunc(sym.log(a, 3), [a])
func10
func10.f([u1])
upy.log(u1, 3)

func10.f([u1]).uncertainty
upy.log(u1, 3).uncertainty
upy.log([u1, u2, u3], 3)

log(a)/log(3)

0.4 ± 0.1

0.4 ± 0.1

0.12136523021691165

0.12136523021691166

array([0.4 ± 0.1, 1 ± 1, 2.1 ± 0.1], dtype=object)

In [18]:
func11 = upy.ufunc(a*sym.log(b*c), [a, b, c])
func11
func11.f([u1, u2, u3])
u1*upy.log(u2*u3)

func11.f([u1, u2, u3]).uncertainty
(u1*upy.log(u2*u3)).uncertainty

a*log(b*c)

5 ± 1

5 ± 1

0.9978250958130539

0.9978250958130537

In [30]:
#sqrt
func12 = upy.ufunc(sym.sqrt(a), [a])
func12
func12.f([u1])
upy.sqrt(u1)

func12.f([u1]).uncertainty
upy.sqrt(u1).uncertainty
upy.sqrt([u1, u2, u3])

sqrt(a)

1.2 ± 0.1

1.2 ± 0.1

0.08164965809277261

0.08164965809277261

array([1.2 ± 0.1, 1.7 ± 0.4, 2.8 ± 0.2], dtype=object)

In [38]:
#trigonometry
#sin
func13 = upy.ufunc(sym.sin(a), [a])
func13
func13.f([u1])
upy.sin(u1)

func13.f([u1]).uncertainty
upy.sin(u1).uncertainty
upy.sin([u1, u2, u3])

sin(a)

1.00 ± 0.01

1.00 ± 0.01

0.014147440333540581

0.014147440333540581

array([1.00 ± 0.01, 0 ± 1, 1.0 ± 0.1], dtype=object)

In [33]:
#cos
func14 = upy.ufunc(sym.cos(a), [a])
func14
func14.f([u1])
upy.cos(u1)

func14.f([u1]).uncertainty
upy.cos(u1).uncertainty
upy.cos([u1, u2, u3])

cos(a)

0.1 ± 0.2

0.1 ± 0.2

0.1994989973208109

0.1994989973208109

array([0.1 ± 0.2, -1.0 ± 0.2, 0 ± 1], dtype=object)

In [35]:
#tan
func15 = upy.ufunc(sym.tan(a), [a])
func15
func15.f([u1])
upy.tan(u1)

func15.f([u1]).uncertainty
upy.tan(u1).uncertainty
upy.tan([u1, u2, u3])

tan(a)

(1 ± 4)x10

(1 ± 4)x10

39.9700089052985

39.9700089052985

array([(1 ± 4)x10, 0 ± 2, (0 ± 2)x10^2], dtype=object)

In [42]:
#csc
func16 = upy.ufunc(sym.csc(a), [a])
func16
func16.f([u1])
upy.csc(u1)
1/upy.sin(u1)

func16.f([u1]).uncertainty
upy.csc(u1).uncertainty
(1/upy.sin(u1)).uncertainty
upy.csc([u1, u2, u3])

csc(a)

1.00 ± 0.01

1.00 ± 0.01

1.00 ± 0.01

0.014218586610461107

0.014218586610461107

0.014218586610461107

array([1.00 ± 0.01, (1 ± 7)x10, 1.0 ± 0.1], dtype=object)

In [41]:
#sec
func17 = upy.ufunc(sym.sec(a), [a])
func17
func17.f([u1])
upy.sec(u1)
1/upy.cos(u1)

func17.f([u1]).uncertainty
upy.sec(u1).uncertainty
(1/upy.cos(u1)).uncertainty
upy.sec([u1, u2, u3])

sec(a)

(1 ± 4)x10

(1 ± 4)x10

(1 ± 4)x10

39.86988349755466

39.86988349755466

39.86988349755466

array([(1 ± 4)x10, -1.0 ± 0.2, (0 ± 2)x10^2], dtype=object)

In [43]:
#cot
func18 = upy.ufunc(sym.cot(a), [a])
func18
func18.f([u1])
upy.cot(u1)
1/upy.tan(u1)

func18.f([u1]).uncertainty`
upy.cot(u1).uncertainty
(1/upy.tan(u1)).uncertainty
upy.cot([u1, u2, u3])

cot(a)

0.1 ± 0.2

0.1 ± 0.2

0.1 ± 0.2

0.2010057830284939

0.2010057830284939

0.20100578302849395

array([0.1 ± 0.2, (-1 ± 8)x10, 0 ± 1], dtype=object)